-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgUHInbC2bD2HUKDDq
MkcRpxi2rdSOqYyUw1CdHawnV42gCgYIKoZIzj0DAQehRANCAAQUACahI/qzxlwi
15UhfIiSCFfE9qi6MXrEJOgdarkBk+8bgyvi9GA4ZGbFMFhKMksGvD6d57AgE6/S
QuPqdTCA
-----END PRIVATE KEY-----